services: 
  myportfolio:
    container_name: myportfolio 
    build: .
    restart: always 
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "5001:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql 
    image: mariadb 
    restart: always 
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mydatabase:/var/lib/mysql

volumes: 
  mydatabase: